include: package:lints/recommended.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_dynamic_calls: true
    camel_case_types: true
    empty_statements: true
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    collection_methods_unrelated_type: true
    comment_references: true
    control_flow_in_finally: true
    deprecated_member_use_from_same_package: true
    discarded_futures: true
    hash_and_equals: true
    implicit_reopen: true
    invalid_case_patterns: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_self_assignments: true
    no_wildcard_variable_uses: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    valid_regexps: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    annotate_redeclares: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_returning_this: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    combinators_ordering: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    dangling_library_doc_comments: true
    directives_ordering: true
    do_not_use_environment: true
    eol_at_end_of_file: true
    file_names: true
    implementation_imports: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_annotations: true
    library_names: true
    library_prefixes: true
    lines_longer_than_80_chars: true
    matching_super_parameters: true
    missing_whitespace_between_adjacent_strings: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    no_literal_bool_comparisons: true
    noop_primitive_operations: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    package_api_docs: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_const_declarations: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_mixin: true
    prefer_single_quotes: true
    public_member_api_docs: true
    require_trailing_commas:
      exclude: "*.g.dart"
      enable: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_lambdas: true
    unnecessary_library_directive: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    unreachable_from_main: true
    use_enums: true
    use_function_type_syntax_for_parameters: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    use_test_throws_matchers: true
    void_checks: true
    depend_on_referenced_packages: true
    package_names: true
    secure_pubspec_urls: true
    sort_pub_dependencies: true

analyzer:
  language:
    strict-casts: true
    strict-inference: false
    strict-raw-types: true
