name: vkdart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.0
  dotenv: ^4.0.1
  json_serializable: ^6.5.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies: { dio: ^4.0.6, json_annotation: ^4.7.0 }
