name: vkdart
description: Library for interacting with Vkontakte API
version: 1.0.2
homepage: https://github.com/swedesjs/vkdart

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.0
  dotenv: ^4.0.1
  json_serializable: ^6.5.1
  lints: ^2.0.0
  test: ^1.16.0

dependencies: { dia: ^0.1.3, dia_body: ^0.1.2, dio: ^5.3.2, json_annotation: ^4.7.0 }
