name: vkdart
description: Package helps simplify working with the VK API.
  Completely wraps VK methods, has event support and much more.
version: 2.2.0
repository: https://github.com/swedesjs/vkdart
issue_tracker: https://github.com/swedesjs/vkdart/issues

topics:
  - vkontakte
  - vk
  - api
  - vk-api
  - http

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  dotenv: ^4.0.1
  lints: ^2.0.0
  shouldly: ^0.5.0+1
  test: ^1.16.0

dependencies: { http: ^1.2.0 }
