name: Check generated .g files

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Check Version DartSDK
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Build .g.dart files
        run: sh -c ./build.sh

      - name: Run git diff
        run: if [[ `git status --porcelain` ]]; then echo "Please re-run `build.sh`"; exit 1; else exit 0; fi;
