name: vkdart

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    env:
      TOKEN: ${{ secrets.TOKEN }}
      GROUP_ID: ${{ secrets. GROUP_ID }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Dart Test
        run: dart test
